http://localhost:4000/randnum

###
http://localhost:4000/randnum?start=5&end=15


###

http://localhost:4000/ranperson

###
http://localhost:4000/ranperson?firstname=true&lastname=true&avatar=true

###
http://localhost:4000/countletnumsym?string=fs@army2023


###
http://localhost:4000/habijabi
